name: hassah_book_flutter
description: The client for Hassah Book.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  shared_preferences: ^0.5.12+4
  graphql_flutter: ^4.0.1
  dio: ^3.0.10
  http: ^0.12.2
  flutter_hooks: ^0.16.0
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  artemis: ^6.18.4
  build_runner: ^1.10.11
  json_serializable: ^3.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Dubai
      fonts:
        - asset: assets/fonts/DubaiW23-Bold.ttf
          weight: 700
        - asset: assets/fonts/DubaiW23-Medium.ttf
          weight: 500
        - asset: assets/fonts/DubaiW23-Regular.ttf
          weight: 400
        - asset: assets/fonts/DubaiW23-Light.ttf
          weight: 300
