name: hassah_book_flutter
description: The client for Hassah Book.

publish_to: "none"
version: 1.0.4+5

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

  graphql_flutter: ^5.1.0
  dio: ^4.0.4
  http: ^0.13.4
  flutter_hooks: ^0.18.2
  flutter_slidable: ^1.2.0
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  webview_flutter: ^3.0.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  # artemis:
  build_runner: ^2.1.7
  json_serializable: ^6.2.0
  hive_generator: ^1.1.2
  flutter_launcher_icons: ^0.9.2
  graphql_codegen: ^0.8.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon_transparent.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Dubai
      fonts:
        - asset: assets/fonts/DubaiW23-Bold.ttf
          weight: 700
        - asset: assets/fonts/DubaiW23-Medium.ttf
          weight: 500
        - asset: assets/fonts/DubaiW23-Regular.ttf
          weight: 400
        - asset: assets/fonts/DubaiW23-Light.ttf
          weight: 300
