name: hassah_book_flutter
description: The client for Hassah Book.

publish_to: "none"
version: 1.0.4+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

  graphql_flutter: ^5.0.1-beta.3
  dio:
  http:
  flutter_hooks:
  flutter_slidable:
  flutter_svg:
  provider:
  webview_flutter:
  hive:
  hive_flutter:
  intl:
  carousel_slider:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

  artemis:
  build_runner:
  json_serializable:
  hive_generator:
  flutter_launcher_icons:
  graphql_codegen: ^0.5.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon_transparent.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Dubai
      fonts:
        - asset: assets/fonts/DubaiW23-Bold.ttf
          weight: 700
        - asset: assets/fonts/DubaiW23-Medium.ttf
          weight: 500
        - asset: assets/fonts/DubaiW23-Regular.ttf
          weight: 400
        - asset: assets/fonts/DubaiW23-Light.ttf
          weight: 300
